--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3
-- Dumped by pg_dump version 13.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: courses; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.courses (
    course_id bigint NOT NULL,
    course_name character varying(255)
);


ALTER TABLE public.courses OWNER TO test;

--
-- Name: courses_course_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.courses ALTER COLUMN course_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grades; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.grades (
    grade_id bigint NOT NULL,
    grade smallint,
    lesson_id bigint,
    student_id bigint
);


ALTER TABLE public.grades OWNER TO test;

--
-- Name: grades_grade_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.grades ALTER COLUMN grade_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grades_grade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: groups; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.groups (
    group_id bigint NOT NULL,
    group_name character varying(255) NOT NULL,
    course_id bigint
);


ALTER TABLE public.groups OWNER TO test;

--
-- Name: groups_group_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.groups ALTER COLUMN group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lessons; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.lessons (
    lesson_id bigint NOT NULL,
    "time" timestamp without time zone,
    group_id bigint,
    teacher_id bigint,
    theme_id bigint,
    lessons_group bigint
);


ALTER TABLE public.lessons OWNER TO test;

--
-- Name: lessons_lesson_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.lessons ALTER COLUMN lesson_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_lesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.students (
    student_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    group_id bigint
);


ALTER TABLE public.students OWNER TO test;

--
-- Name: students_student_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.students ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teachers; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.teachers (
    teacher_id bigint NOT NULL,
    name character varying(255),
    surname character varying(255)
);


ALTER TABLE public.teachers OWNER TO test;

--
-- Name: teachers_teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.teachers ALTER COLUMN teacher_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teachers_teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: themes; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.themes (
    theme_id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.themes OWNER TO test;

--
-- Name: themes_theme_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.themes ALTER COLUMN theme_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.themes_theme_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: test
--

COPY public.courses (course_id, course_name) FROM stdin;
1	java
\.


--
-- Data for Name: grades; Type: TABLE DATA; Schema: public; Owner: test
--

COPY public.grades (grade_id, grade, lesson_id, student_id) FROM stdin;
1	10	1	2
\.


--
-- Data for Name: groups; Type: TABLE DATA; Schema: public; Owner: test
--

COPY public.groups (group_id, group_name, course_id) FROM stdin;
1	nix 5 online	1
2	nix 6 online	1
\.


--
-- Data for Name: lessons; Type: TABLE DATA; Schema: public; Owner: test
--

COPY public.lessons (lesson_id, "time", group_id, teacher_id, theme_id, lessons_group) FROM stdin;
1	2021-07-22 22:43:56.355	1	1	1	1
2	2021-07-27 22:43:56.361	2	1	2	2
\.


--
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: test
--

COPY public.students (student_id, name, surname, group_id) FROM stdin;
1	Some	Student	2
2	Vlad	Liasota	1
\.


--
-- Data for Name: teachers; Type: TABLE DATA; Schema: public; Owner: test
--

COPY public.teachers (teacher_id, name, surname) FROM stdin;
1	Some	Teacher
\.


--
-- Data for Name: themes; Type: TABLE DATA; Schema: public; Owner: test
--

COPY public.themes (theme_id, name) FROM stdin;
1	jpa/jdbc
2	reflection
\.


--
-- Name: courses_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: test
--

SELECT pg_catalog.setval('public.courses_course_id_seq', 1, true);


--
-- Name: grades_grade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: test
--

SELECT pg_catalog.setval('public.grades_grade_id_seq', 1, true);


--
-- Name: groups_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: test
--

SELECT pg_catalog.setval('public.groups_group_id_seq', 2, true);


--
-- Name: lessons_lesson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: test
--

SELECT pg_catalog.setval('public.lessons_lesson_id_seq', 2, true);


--
-- Name: students_student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: test
--

SELECT pg_catalog.setval('public.students_student_id_seq', 2, true);


--
-- Name: teachers_teacher_id_seq; Type: SEQUENCE SET; Schema: public; Owner: test
--

SELECT pg_catalog.setval('public.teachers_teacher_id_seq', 1, true);


--
-- Name: themes_theme_id_seq; Type: SEQUENCE SET; Schema: public; Owner: test
--

SELECT pg_catalog.setval('public.themes_theme_id_seq', 2, true);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (course_id);


--
-- Name: grades grades_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT grades_pkey PRIMARY KEY (grade_id);


--
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (group_id);


--
-- Name: lessons lessons_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (lesson_id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (student_id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (teacher_id);


--
-- Name: themes themes_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.themes
    ADD CONSTRAINT themes_pkey PRIMARY KEY (theme_id);


--
-- Name: grades fk$student_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fk$student_id FOREIGN KEY (student_id) REFERENCES public.students(student_id);


--
-- Name: lessons fk$theme_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk$theme_id FOREIGN KEY (theme_id) REFERENCES public.themes(theme_id);


--
-- Name: lessons fk$lesson_teacher; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk$lesson_teacher FOREIGN KEY (teacher_id) REFERENCES public.teachers(teacher_id);


--
-- Name: lessons fk$lesson_teacher_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk$lesson_teacher_id FOREIGN KEY (teacher_id) REFERENCES public.teachers(teacher_id);


--
-- Name: groups fk$group_course; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fk$group_course FOREIGN KEY (course_id) REFERENCES public.courses(course_id);


--
-- Name: students fk$group_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fk$group_id FOREIGN KEY (group_id) REFERENCES public.groups(group_id);


--
-- Name: grades fk$lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fk$lesson_id FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id);


--
-- Name: lessons fk$lessons_group; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk$lessons_group FOREIGN KEY (lessons_group) REFERENCES public.groups(group_id);


--
-- Name: lessons fk$group_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk$group_id FOREIGN KEY (group_id) REFERENCES public.groups(group_id);


--
-- PostgreSQL database dump complete
--

